spring.application.name=demo-upstream

server.address=127.0.0.1
server.port=8081

spring.ai.mcp.server.name=contextguard-demo-upstream
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC

spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
spring.ai.mcp.server.capabilities.completion=false
